### ISSUE TITLE
Как отобразить загруженные из БД картинки/файлы?

### ISSUE THREAD

**Issue by ghost** [shabuninil/fileup#2]
Игорь, приветствую!
Задача такая. Есть две страницы: добавление файлов и редактирование файлов. Со страницей добавления все понятно. Я подключаю ваш плагин и делаю все как в сказано в документации. Далее, картинки добавляются в БД.
А как быть на странице редактирования картинок? Т.е. зайдя на страницу редактирования, мне надо подгрузить картинки/файлы из БД и вывести в таком же виде, как при добавлении. С возможностью удаления, как старых, так и добавления новых картинок/файлов?
Каким методом можно реализовать это в вашем плагине и возможно ли это?
Спасибо!

**Comment by n2ref** [comment]
Привет.
К сожалению, готового для этого метода или свойства нету и поэтому это нужно делать самому.
Раз к библиотеке появляется интерес, то думаю найду время и сделаю такой, возможно в этом месяце.

Когда я этим занимался, то я делал это так:
1. При рендере страницы, или уже позже, в div queueID вставляется html с аналогичной структурой для файлов, которую генерит библиотека. 
2. Добавляется скрытое поле для передачи на сервер идентификаторов удаленных файлов.
3. Добавляется небольшой скрипт который заботится об пометке файлов как удаленных

У меня это было примерно так
```html
<input type="hidden" id="control_del" name="file_del" value="">

<div id="upload-[ID]-queue">
    <div id="file-[KEY]" class="fileup-file [TYPE]" data-file-id="[ID]" data-file-container="file-[KEY]">
        <div class="preview">
             <img src="[PREVIEW_URL]" alt="[ALT]"/>
         </div>
         <div class="data">
             <div class="description">
                 <span class="file-name">[NAME]</span>
                 (<span class="file-size">[SIZE_HUMAN]</span>)
                  <a href="[DOWNLOAD_URL]" class="file-name" download="[NAME]">[NAME]</a>
                  <span class="file-size">([SIZE_HUMAN])</span>
             </div>
             <div class="controls">
                  <span class="remove" title="Удалить"></span>
             </div>
         </div>
         <div class="clear"></div>
     </div>

    ............

</div>

<script type="text/javascript">
        $('#upload-[ID]-queue .fileup-file .remove').click(function(){
            var $container = $(this).parent().parent().parent();
            var file_id        = $container.data('file-id');
            $container.fadeOut('fast', function(){
                var control_del = document.getElementById('control_del');
                if (control_del.value !== '') {
                    control_del.value += ',' + file_id;
                } else {
                    control_del.value = file_id;
                }
                $(this).remove();
            })
        });


       $.fileup({
            ...

            onRemove : function(file, total) {
                if (file == '*' || total == 1) {
                    $('#upload-[ID]-queue .uploadH5-file[data-file-id]').each(function(i, container){
                        var file_id           = $(container).data('file-id');
                        var file_container_id = $(container).data('file-container');
                        $('#' + file_container_id).fadeOut('fast', function(){
                            var control_del = document.getElementById('control_del');
                            if (control_del.value !== '') {
                                control_del.value += ',' + file_id;
                            } else {
                                control_del.value = file_id;
                            }
                            $(this).remove();
                        })
                    });
                    document.getElementById('[ID]').value = '';
                    $('.control-button').hide();
                }
            }
            ...
        });

</script>

```
Если будут вопросы, то обращайтесь.

**Comment by ghost** [comment]
Игорь, большое спасибо за ответ!
Я просто хочу такой же функционал загрузки файлов, как на Авито (если вы зарегистрированы там). Если сможете его реализовать, то это будет просто замечательно!
Спасибо!

**Comment by n2ref** [comment]
Я посмотрел как сделано на Авито и сделать как там можно. Но к сожалению, сейчас у меня большая загруженность по своей работе и я не могу найти на это время. В будущем постараюсь добавить удобство работы с библиотекой и поддержку разных шкурок.

**Comment by ghost** [comment]
Игорь, спасибо!
Буду ждать, когда реализуете, ибо очень надо. Готов закинуть донат :)

**Comment by n2ref** [comment]
Добрый день.
Нашел время заняться библиотекой.
Пример того что вам надо тут [https://shabuninil.github.io/fileup/#example-theme2](https://shabuninil.github.io/fileup/#example-theme2)
