### ISSUE TITLE
Работа в мобильном Firefox

### ISSUE THREAD

**Issue by nevstas** [shabuninil/fileup#3]
Игорь привет!
1) Работает ли fileup в мобильном Firefox?
2) Не верные ссылки на css и js по этой ссылке https://shabuninil.github.io/fileup/ 
[Скрин](https://nevep.ru/screenshots/s30xrdhv94nsshz8ivlc-2019-11-04_18-30-24.png)

**Comment by n2ref** [comment]
Привет. Да, в Firefox все должно работать. Что-то не работает?
Ссылки да, перепутаны местами, поменяю, спасибо )

**Comment by nevstas** [comment]
А, все, заработало) Видимо кеш
Извиняй что отвлек
