### ISSUE TITLE
how to restrict files type

### ISSUE THREAD

**Issue by snake-venom-nk** [shabuninil/fileup#4]
Hello, this is really impressive work, the lightweight plugin for uploading files.
Do you decide to update your document to restrict the file type,  when the user only wants to upload mp4 or video files?

Please guide me here too quickly.

**Comment by n2ref** [comment]
I don't quite understand what you are talking about. Please clarify

**Comment by snake-venom-nk** [comment]
> I don't quite understand what you are talking about. Please clarify

I am trying to validate the files not to upload image format. 
case: if I setup this uploader to upload only video audio files then images should not upload. Where I can add an array of formats which format should not upload.

**Comment by n2ref** [comment]
If you need to restrict the type of uploaded files, then you need to use the accept attribute. This is a standard html attribute and my plugin will use it.

https://developer.mozilla.org/ru/docs/Web/HTML/Element/Input/file#limiting_accepted_file_types

To upload only videos, you must specify `accept="video/*" `
If you need both video and audio, then `accept="video/*,audio/*" `
If you need a list of formats from, you can list them separated by commas `accept=".mp4,.wav" `

Try it. If you have questions, then ask
